
GET http://localhost:8080/users HTTP/1.1
content-type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI2NGI0MWI0LTM1YzgtNDI2Ny1hYWVkLTNlODBkOWUyMTJkZiIsInVzZXJuYW1lIjoicmVjcnV0YWRvckBncm93ZGV2LmNvbS5iciIsInByb2ZpbGUiOiJSRUNSVUlURVIiLCJjb21wYW55IjoiR3Jvd2RldiIsImlhdCI6MTY5NDIyMzA0NiwiZXhwIjoxNjk0MjI2NjQ2fQ.HqUy5HJhdR_S4N9NlCeWpTXWYXIKWKB26-VQ7rGpVKg
